-- =========================================================
-- SKYROVIX — Real-World Project Challenge Seed Data
-- Run this AFTER migrations-projects.sql
-- =========================================================

INSERT INTO public.project_challenges (project_id, title, industry, difficulty, business_background, problem_statement, business_requirements, functional_requirements, technical_requirements, expected_deliverables, evaluation_criteria, technologies, submission_deadline, is_published, resources)
VALUES
(
  'PRJ-2026-001',
  'Smart Inventory Management System',
  'Retail & E-Commerce',
  'intermediate',
  'A mid-sized retail chain with 50+ stores across India struggles with manual inventory tracking. Stockouts cost ₹2Cr/month in lost revenue, and excess inventory ties up ₹5Cr in working capital. They need a real-time inventory system that predicts demand and automates reordering.',
  'Design and build a smart inventory management platform that provides real-time stock visibility across all stores, predicts demand using historical sales data, and automates purchase orders when stock falls below threshold levels.',
  ARRAY['Real-time inventory tracking across 50+ stores', 'Automated low-stock alerts via email/SMS', 'Role-based access for store managers, regional heads, and admin', 'Integration with existing billing systems', 'Support for 10,000+ SKUs'],
  ARRAY['Dashboard showing stock levels by store/category', 'Predictive demand forecasting using sales history', 'Auto-generate purchase orders at reorder points', 'Barcode/QR code scanning for stock updates', 'Inventory transfer between stores', 'Monthly reconciliation reports'],
  ARRAY['React + TypeScript frontend', 'Node.js/Python backend with REST API', 'PostgreSQL with proper indexing', 'Redis for real-time stock caching', 'JWT authentication', 'Responsive web design'],
  ARRAY['Working web application', 'API documentation', 'Database schema', 'Deployment guide', 'Demo video (5 min)'],
  ARRAY['Problem Solving Approach', 'UI/UX Design', 'Functionality', 'Code Quality', 'Application Architecture', 'Database Design', 'Performance', 'Documentation', 'Innovation'],
  ARRAY['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redis'],
  '2026-09-30T23:59:59Z',
  true,
  '[{"label":"Retail Inventory Best Practices","url":"https://example.com/inventory-guide"},{"label":"Demand Forecasting Methods","url":"https://example.com/demand-forecast"}]'
),
(
  'PRJ-2026-002',
  'Telemedicine Consultation Platform',
  'Healthcare',
  'advanced',
  'Rural India faces a severe shortage of specialists — 80% of doctors serve urban areas while 65% of the population lives in rural regions. A healthcare startup wants to build a telemedicine platform connecting rural patients with specialists via video consultation, with integrated prescription management and medical record storage.',
  'Build a HIPAA-compliant telemedicine platform that enables patients to book appointments with specialists, conduct video consultations, receive e-prescriptions, and maintain a lifelong digital health record accessible across hospitals.',
  ARRAY['Doctor-patient video consultations', 'E-prescription with digital signature', 'Secure medical record storage (lifelong)', 'Appointment scheduling with calendar sync', 'Integration with pharmacy partners for medicine delivery'],
  ARRAY['Patient registration with Aadhaar/phone', 'Doctor profile with specialization search', 'Slot booking with real-time availability', 'Video call with chat and file sharing', 'Digital prescription generation', 'Lab report upload and storage', 'SMS/WhatsApp appointment reminders'],
  ARRAY['React/Next.js frontend', 'WebRTC for video calls (100ms/Twilio)', 'Node.js + PostgreSQL backend', 'AES-256 encryption for medical records', 'FHIR-compliant data models', 'Docker containerization'],
  ARRAY['Working web app with video consultation', 'API documentation', 'Database schema design', 'Security audit report', 'Deployment on cloud'],
  ARRAY['Problem Solving Approach', 'UI/UX Design', 'Functionality', 'Code Quality', 'Application Architecture', 'Database Design', 'Performance', 'Security', 'Scalability', 'Documentation'],
  ARRAY['Next.js', 'WebRTC', 'Node.js', 'PostgreSQL', 'Docker', 'AES-256'],
  '2026-10-15T23:59:59Z',
  true,
  '[{"label":"HIPAA Compliance Guide","url":"https://example.com/hipaa"},{"label":"Telemedicine Architecture","url":"https://example.com/telemed-arch"}]'
),
(
  'PRJ-2026-003',
  'AI-Powered Resume Screener & Job Matcher',
  'HR Technology',
  'expert',
  'A growing recruitment agency processes 5,000+ resumes weekly. Recruiters spend 70% of their time manually screening resumes. They need an AI system that automatically parses resumes, extracts key skills, screens candidates against job descriptions, and ranks applicants by fit score.',
  'Develop an AI-powered resume screening and job matching platform that uses NLP to parse resumes in multiple formats (PDF, DOCX, LinkedIn exports), extracts structured data, matches candidates to job descriptions using semantic similarity, and provides explainable rankings.',
  ARRAY['Parse 15+ resume formats accurately', 'Extract 30+ fields (skills, experience, education, etc.)', 'Semantic matching against job descriptions', 'Explainable AI — show why candidate matches', 'Batch processing of 1000+ resumes/hr'],
  ARRAY['Drag-and-drop resume upload', 'ATS-style candidate ranking dashboard', 'JD creation with skill weightage', 'Candidate shortlist with comparison view', 'Email integration for interview scheduling', 'Export reports in Excel/PDF', 'API for third-party ATS integration'],
  ARRAY['Python/Flask or FastAPI backend', 'React frontend', 'PostgreSQL + pgvector for embeddings', 'OpenAI/LLM API or local BERT model', 'Celery/Redis for async resume processing', 'Docker + Kubernetes deployment'],
  ARRAY['Working web application', 'ML model performance report (accuracy, F1)', 'API documentation', 'Architecture diagram', 'Demo with 100 sample resumes'],
  ARRAY['Problem Solving Approach', 'Functionality', 'Code Quality', 'Application Architecture', 'Database Design', 'Performance', 'Scalability', 'Documentation', 'Innovation'],
  ARRAY['Python', 'FastAPI', 'React', 'PostgreSQL', 'pgvector', 'Docker', 'Kubernetes', 'BERT/LLM'],
  '2026-11-01T23:59:59Z',
  true,
  '[{"label":"NLP for Resume Parsing","url":"https://example.com/nlp-resume"},{"label":"Semantic Search with pgvector","url":"https://example.com/pgvector"}]'
),
(
  'PRJ-2026-004',
  'Community Food Waste Reduction Platform',
  'Social Impact / Sustainability',
  'beginner',
  'India wastes 67 million tonnes of food annually while 190 million people go hungry daily. Local restaurants and wedding halls discard edible surplus. A nonprofit wants a platform that connects food donors with verified NGOs and community fridges to redistribute surplus food in real-time.',
  'Create a mobile-first web platform that enables restaurants, caterers, and event organizers to list surplus food, which nearby NGOs and individuals can claim and collect, with real-time inventory tracking and impact metrics.',
  ARRAY['Real-time food listing with photos and quantity', 'GPS-based donor-NGO matching within 5km radius', 'Verification system for NGOs (govt registration)', 'Pickup tracking with ETA and confirmation', 'Impact dashboard showing meals saved, CO2 reduced'],
  ARRAY['User registration (donor/recipient)', 'Food listing with expiry time and quantity', 'Map view showing nearby available food', 'Claim & collect workflow with QR confirmation', 'In-app chat between donor and recipient', 'Rating system for trust', 'Monthly impact report generation'],
  ARRAY['React + Tailwind responsive web app', 'Node.js/Express backend', 'PostgreSQL database', 'Mapbox/Google Maps API', 'Firebase Cloud Messaging for notifications', 'PWA support for mobile'],
  ARRAY['Working web application (PWA)', 'API documentation', 'Database schema', 'Impact metrics algorithm', 'User guide'],
  ARRAY['Problem Solving Approach', 'UI/UX Design', 'Functionality', 'Code Quality', 'Application Architecture', 'Database Design', 'Documentation', 'Innovation'],
  ARRAY['React', 'Tailwind', 'Node.js', 'PostgreSQL', 'Mapbox', 'Firebase'],
  '2026-08-30T23:59:59Z',
  true,
  '[{"label":"Food Safety Guidelines for Donation","url":"https://example.com/food-safety"},{"label":"UN SDG 12.3 — Food Waste","url":"https://example.com/un-sdg"}]'
),
(
  'PRJ-2026-005',
  'Cryptocurrency Portfolio Tracker & Alert System',
  'Fintech',
  'intermediate',
  'Retail crypto investors in India lack a unified platform to track their portfolio across multiple exchanges (Binance, CoinDCX, WazirX). They currently maintain manual spreadsheets. A fintech startup wants to build a dashboard that aggregates portfolio data, provides real-time P&L, and sends price alerts.',
  'Build a cryptocurrency portfolio tracker that connects to multiple exchange APIs, syncs transactions automatically, computes real-time P&L, tracks cost basis for tax reporting, and provides customizable price alerts via Telegram/Email.',
  ARRAY['Connect to 5+ Indian/global exchange APIs', 'Automatic transaction sync from exchange history', 'Real-time P&L with cost basis (FIFO/Weighted Avg)', 'Tax lot tracking for Indian income tax compliance', 'Price alerts with Telegram/Email/SMS'],
  ARRAY['User portfolio dashboard with charts', 'Manual entry fallback for unsupported exchanges', 'P&L breakdown by coin, exchange, timeframe', 'Transaction history with filter/search', 'Alert creation with price threshold and trigger', 'Tax report export (CSV/PDF)', 'Coin news and sentiment feed'],
  ARRAY['React dashboard with charts (TradingView/Chart.js)', 'Node.js backend with cron job scheduler', 'PostgreSQL for transaction data', 'Redis for real-time price cache', 'WebSocket for live price updates', 'Docker deployment'],
  ARRAY['Working web application', 'API documentation', 'Sample exchange integration code', 'Database schema', 'Deployment guide'],
  ARRAY['Problem Solving Approach', 'UI/UX Design', 'Functionality', 'Code Quality', 'Application Architecture', 'Database Design', 'Performance', 'Security', 'Documentation'],
  ARRAY['React', 'Node.js', 'PostgreSQL', 'Redis', 'WebSocket', 'Chart.js'],
  '2026-09-15T23:59:59Z',
  true,
  '[{"label":"Crypto Tax Guide India","url":"https://example.com/crypto-tax"},{"label":"Exchange API docs — Binance","url":"https://binance-docs.github.io"}]'
),
(
  'PRJ-2026-006',
  'Smart Classroom Engagement Analytics',
  'Education Technology',
  'advanced',
  'A chain of 20+ coaching institutes in Tamil Nadu with 10,000+ students wants to move beyond traditional teaching. Teachers report that 40% of students disengage during online classes. They need an AI system that analyzes student engagement in real-time during live classes and provides actionable insights to teachers.',
  'Develop a classroom engagement analytics platform that uses computer vision and behavioral analysis to measure student attention levels during live video classes, provides real-time engagement scores to teachers, and generates post-class analytics reports.',
  ARRAY['Real-time engagement detection via webcam', 'Per-student attention score every 30 seconds', 'Class-level engagement heatmap', 'Teacher dashboard with real-time nudges', 'Post-class analytics with recommendations'],
  ARRAY['Classroom creation with student roster', 'Webcam-based attention analysis (head pose, gaze, facial expressions)', 'Real-time engagement dashboard for teachers', 'Low-engagement alerts (visual + sound)', 'Auto-generated post-class report with AI suggestions', 'Student progress tracking over semester', 'Integration with Zoom/Google Meet'],
  ARRAY['Python/Flask for ML inference', 'React/Typescript frontend', 'OpenCV + MediaPipe for facial analysis', 'TensorFlow/PyTorch for engagement model', 'WebSocket for real-time data push', 'PostgreSQL for analytics storage', 'Docker + GPU support'],
  ARRAY['Working prototype with live demo', 'ML model accuracy report', 'API documentation', 'Architecture diagram', 'Integration guide for Zoom/Meet'],
  ARRAY['Problem Solving Approach', 'Functionality', 'Code Quality', 'Application Architecture', 'Performance', 'Security', 'Scalability', 'Documentation', 'Innovation'],
  ARRAY['Python', 'React', 'OpenCV', 'TensorFlow', 'WebSocket', 'PostgreSQL', 'Docker'],
  '2026-10-30T23:59:59Z',
  true,
  '[{"label":"MediaPipe Face Mesh Guide","url":"https://google.github.io/mediapipe"},{"label":"Student Engagement Detection Research","url":"https://example.com/engagement-paper"}]'
)
ON CONFLICT (project_id) DO NOTHING;
