/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as NavbarLayoutRouteImport } from './routes/_navbar-layout'
import { Route as DomainsIndexRouteImport } from './routes/domains.index'
import { Route as NavbarLayoutIndexRouteImport } from './routes/_navbar-layout/index'
import { Route as DomainsSlugRouteImport } from './routes/domains.$slug'
import { Route as NavbarLayoutAboutRouteImport } from './routes/_navbar-layout/about'
import { Route as NavbarLayoutAuthenticatedRouteRouteImport } from './routes/_navbar-layout/_authenticated/route'
import { Route as NavbarLayoutProjectsIndexRouteImport } from './routes/_navbar-layout/projects.index'
import { Route as NavbarLayoutCoursesIndexRouteImport } from './routes/_navbar-layout/courses.index'
import { Route as ApiCronCleanupSessionsRouteImport } from './routes/api.cron.cleanup-sessions'
import { Route as NavbarLayoutProjectsIdRouteImport } from './routes/_navbar-layout/projects.$id'
import { Route as NavbarLayoutCoursesSlugRouteImport } from './routes/_navbar-layout/courses.$slug'
import { Route as NavbarLayoutAuthenticatedReviewRouteImport } from './routes/_navbar-layout/_authenticated/review'
import { Route as NavbarLayoutAuthenticatedDashboardRouteImport } from './routes/_navbar-layout/_authenticated/dashboard'
import { Route as NavbarLayoutProjectsIdSubmitRouteImport } from './routes/_navbar-layout/projects.$id_.submit'
import { Route as NavbarLayoutCoursesSlugQuizRouteImport } from './routes/_navbar-layout/courses.$slug_.quiz'
import { Route as NavbarLayoutCoursesSlugDetailsRouteImport } from './routes/_navbar-layout/courses.$slug_.details'

const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutRoute = NavbarLayoutRouteImport.update({
  id: '/_navbar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsRoute,
} as any)
const NavbarLayoutIndexRoute = NavbarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const DomainsSlugRoute = DomainsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DomainsRoute,
} as any)
const NavbarLayoutAboutRoute = NavbarLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutAuthenticatedRouteRoute =
  NavbarLayoutAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => NavbarLayoutRoute,
  } as any)
const NavbarLayoutProjectsIndexRoute =
  NavbarLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => NavbarLayoutRoute,
  } as any)
const NavbarLayoutCoursesIndexRoute =
  NavbarLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => NavbarLayoutRoute,
  } as any)
const ApiCronCleanupSessionsRoute = ApiCronCleanupSessionsRouteImport.update({
  id: '/api/cron/cleanup-sessions',
  path: '/api/cron/cleanup-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutProjectsIdRoute = NavbarLayoutProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutCoursesSlugRoute = NavbarLayoutCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutAuthenticatedReviewRoute =
  NavbarLayoutAuthenticatedReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => NavbarLayoutAuthenticatedRouteRoute,
  } as any)
const NavbarLayoutAuthenticatedDashboardRoute =
  NavbarLayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => NavbarLayoutAuthenticatedRouteRoute,
  } as any)
const NavbarLayoutProjectsIdSubmitRoute =
  NavbarLayoutProjectsIdSubmitRouteImport.update({
    id: '/projects/$id_/submit',
    path: '/projects/$id/submit',
    getParentRoute: () => NavbarLayoutRoute,
  } as any)
const NavbarLayoutCoursesSlugQuizRoute =
  NavbarLayoutCoursesSlugQuizRouteImport.update({
    id: '/courses/$slug_/quiz',
    path: '/courses/$slug/quiz',
    getParentRoute: () => NavbarLayoutRoute,
  } as any)
const NavbarLayoutCoursesSlugDetailsRoute =
  NavbarLayoutCoursesSlugDetailsRouteImport.update({
    id: '/courses/$slug_/details',
    path: '/courses/$slug/details',
    getParentRoute: () => NavbarLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof NavbarLayoutIndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/domains': typeof DomainsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/about': typeof NavbarLayoutAboutRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/domains/': typeof DomainsIndexRoute
  '/dashboard': typeof NavbarLayoutAuthenticatedDashboardRoute
  '/review': typeof NavbarLayoutAuthenticatedReviewRoute
  '/courses/$slug': typeof NavbarLayoutCoursesSlugRoute
  '/projects/$id': typeof NavbarLayoutProjectsIdRoute
  '/api/cron/cleanup-sessions': typeof ApiCronCleanupSessionsRoute
  '/courses/': typeof NavbarLayoutCoursesIndexRoute
  '/projects/': typeof NavbarLayoutProjectsIndexRoute
  '/courses/$slug/details': typeof NavbarLayoutCoursesSlugDetailsRoute
  '/courses/$slug/quiz': typeof NavbarLayoutCoursesSlugQuizRoute
  '/projects/$id/submit': typeof NavbarLayoutProjectsIdSubmitRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/': typeof NavbarLayoutIndexRoute
  '/about': typeof NavbarLayoutAboutRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/domains': typeof DomainsIndexRoute
  '/dashboard': typeof NavbarLayoutAuthenticatedDashboardRoute
  '/review': typeof NavbarLayoutAuthenticatedReviewRoute
  '/courses/$slug': typeof NavbarLayoutCoursesSlugRoute
  '/projects/$id': typeof NavbarLayoutProjectsIdRoute
  '/api/cron/cleanup-sessions': typeof ApiCronCleanupSessionsRoute
  '/courses': typeof NavbarLayoutCoursesIndexRoute
  '/projects': typeof NavbarLayoutProjectsIndexRoute
  '/courses/$slug/details': typeof NavbarLayoutCoursesSlugDetailsRoute
  '/courses/$slug/quiz': typeof NavbarLayoutCoursesSlugQuizRoute
  '/projects/$id/submit': typeof NavbarLayoutProjectsIdSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_navbar-layout': typeof NavbarLayoutRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/domains': typeof DomainsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/_navbar-layout/_authenticated': typeof NavbarLayoutAuthenticatedRouteRouteWithChildren
  '/_navbar-layout/about': typeof NavbarLayoutAboutRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/_navbar-layout/': typeof NavbarLayoutIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/_navbar-layout/_authenticated/dashboard': typeof NavbarLayoutAuthenticatedDashboardRoute
  '/_navbar-layout/_authenticated/review': typeof NavbarLayoutAuthenticatedReviewRoute
  '/_navbar-layout/courses/$slug': typeof NavbarLayoutCoursesSlugRoute
  '/_navbar-layout/projects/$id': typeof NavbarLayoutProjectsIdRoute
  '/api/cron/cleanup-sessions': typeof ApiCronCleanupSessionsRoute
  '/_navbar-layout/courses/': typeof NavbarLayoutCoursesIndexRoute
  '/_navbar-layout/projects/': typeof NavbarLayoutProjectsIndexRoute
  '/_navbar-layout/courses/$slug_/details': typeof NavbarLayoutCoursesSlugDetailsRoute
  '/_navbar-layout/courses/$slug_/quiz': typeof NavbarLayoutCoursesSlugQuizRoute
  '/_navbar-layout/projects/$id_/submit': typeof NavbarLayoutProjectsIdSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/domains'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/verify-certificate'
    | '/about'
    | '/domains/$slug'
    | '/domains/'
    | '/dashboard'
    | '/review'
    | '/courses/$slug'
    | '/projects/$id'
    | '/api/cron/cleanup-sessions'
    | '/courses/'
    | '/projects/'
    | '/courses/$slug/details'
    | '/courses/$slug/quiz'
    | '/projects/$id/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/verify-certificate'
    | '/'
    | '/about'
    | '/domains/$slug'
    | '/domains'
    | '/dashboard'
    | '/review'
    | '/courses/$slug'
    | '/projects/$id'
    | '/api/cron/cleanup-sessions'
    | '/courses'
    | '/projects'
    | '/courses/$slug/details'
    | '/courses/$slug/quiz'
    | '/projects/$id/submit'
  id:
    | '__root__'
    | '/_navbar-layout'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/domains'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/verify-certificate'
    | '/_navbar-layout/_authenticated'
    | '/_navbar-layout/about'
    | '/domains/$slug'
    | '/_navbar-layout/'
    | '/domains/'
    | '/_navbar-layout/_authenticated/dashboard'
    | '/_navbar-layout/_authenticated/review'
    | '/_navbar-layout/courses/$slug'
    | '/_navbar-layout/projects/$id'
    | '/api/cron/cleanup-sessions'
    | '/_navbar-layout/courses/'
    | '/_navbar-layout/projects/'
    | '/_navbar-layout/courses/$slug_/details'
    | '/_navbar-layout/courses/$slug_/quiz'
    | '/_navbar-layout/projects/$id_/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NavbarLayoutRoute: typeof NavbarLayoutRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DomainsRoute: typeof DomainsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  ApiCronCleanupSessionsRoute: typeof ApiCronCleanupSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar-layout': {
      id: '/_navbar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/_navbar-layout/': {
      id: '/_navbar-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutIndexRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/domains/$slug': {
      id: '/domains/$slug'
      path: '/$slug'
      fullPath: '/domains/$slug'
      preLoaderRoute: typeof DomainsSlugRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/_navbar-layout/about': {
      id: '/_navbar-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof NavbarLayoutAboutRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/_authenticated': {
      id: '/_navbar-layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutAuthenticatedRouteRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/projects/': {
      id: '/_navbar-layout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof NavbarLayoutProjectsIndexRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/courses/': {
      id: '/_navbar-layout/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof NavbarLayoutCoursesIndexRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/api/cron/cleanup-sessions': {
      id: '/api/cron/cleanup-sessions'
      path: '/api/cron/cleanup-sessions'
      fullPath: '/api/cron/cleanup-sessions'
      preLoaderRoute: typeof ApiCronCleanupSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar-layout/projects/$id': {
      id: '/_navbar-layout/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof NavbarLayoutProjectsIdRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/courses/$slug': {
      id: '/_navbar-layout/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof NavbarLayoutCoursesSlugRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/_authenticated/review': {
      id: '/_navbar-layout/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof NavbarLayoutAuthenticatedReviewRouteImport
      parentRoute: typeof NavbarLayoutAuthenticatedRouteRoute
    }
    '/_navbar-layout/_authenticated/dashboard': {
      id: '/_navbar-layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof NavbarLayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof NavbarLayoutAuthenticatedRouteRoute
    }
    '/_navbar-layout/projects/$id_/submit': {
      id: '/_navbar-layout/projects/$id_/submit'
      path: '/projects/$id/submit'
      fullPath: '/projects/$id/submit'
      preLoaderRoute: typeof NavbarLayoutProjectsIdSubmitRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/courses/$slug_/quiz': {
      id: '/_navbar-layout/courses/$slug_/quiz'
      path: '/courses/$slug/quiz'
      fullPath: '/courses/$slug/quiz'
      preLoaderRoute: typeof NavbarLayoutCoursesSlugQuizRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/courses/$slug_/details': {
      id: '/_navbar-layout/courses/$slug_/details'
      path: '/courses/$slug/details'
      fullPath: '/courses/$slug/details'
      preLoaderRoute: typeof NavbarLayoutCoursesSlugDetailsRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
  }
}

interface NavbarLayoutAuthenticatedRouteRouteChildren {
  NavbarLayoutAuthenticatedDashboardRoute: typeof NavbarLayoutAuthenticatedDashboardRoute
  NavbarLayoutAuthenticatedReviewRoute: typeof NavbarLayoutAuthenticatedReviewRoute
}

const NavbarLayoutAuthenticatedRouteRouteChildren: NavbarLayoutAuthenticatedRouteRouteChildren =
  {
    NavbarLayoutAuthenticatedDashboardRoute:
      NavbarLayoutAuthenticatedDashboardRoute,
    NavbarLayoutAuthenticatedReviewRoute: NavbarLayoutAuthenticatedReviewRoute,
  }

const NavbarLayoutAuthenticatedRouteRouteWithChildren =
  NavbarLayoutAuthenticatedRouteRoute._addFileChildren(
    NavbarLayoutAuthenticatedRouteRouteChildren,
  )

interface NavbarLayoutRouteChildren {
  NavbarLayoutAuthenticatedRouteRoute: typeof NavbarLayoutAuthenticatedRouteRouteWithChildren
  NavbarLayoutAboutRoute: typeof NavbarLayoutAboutRoute
  NavbarLayoutIndexRoute: typeof NavbarLayoutIndexRoute
  NavbarLayoutCoursesSlugRoute: typeof NavbarLayoutCoursesSlugRoute
  NavbarLayoutProjectsIdRoute: typeof NavbarLayoutProjectsIdRoute
  NavbarLayoutCoursesIndexRoute: typeof NavbarLayoutCoursesIndexRoute
  NavbarLayoutProjectsIndexRoute: typeof NavbarLayoutProjectsIndexRoute
  NavbarLayoutCoursesSlugDetailsRoute: typeof NavbarLayoutCoursesSlugDetailsRoute
  NavbarLayoutCoursesSlugQuizRoute: typeof NavbarLayoutCoursesSlugQuizRoute
  NavbarLayoutProjectsIdSubmitRoute: typeof NavbarLayoutProjectsIdSubmitRoute
}

const NavbarLayoutRouteChildren: NavbarLayoutRouteChildren = {
  NavbarLayoutAuthenticatedRouteRoute:
    NavbarLayoutAuthenticatedRouteRouteWithChildren,
  NavbarLayoutAboutRoute: NavbarLayoutAboutRoute,
  NavbarLayoutIndexRoute: NavbarLayoutIndexRoute,
  NavbarLayoutCoursesSlugRoute: NavbarLayoutCoursesSlugRoute,
  NavbarLayoutProjectsIdRoute: NavbarLayoutProjectsIdRoute,
  NavbarLayoutCoursesIndexRoute: NavbarLayoutCoursesIndexRoute,
  NavbarLayoutProjectsIndexRoute: NavbarLayoutProjectsIndexRoute,
  NavbarLayoutCoursesSlugDetailsRoute: NavbarLayoutCoursesSlugDetailsRoute,
  NavbarLayoutCoursesSlugQuizRoute: NavbarLayoutCoursesSlugQuizRoute,
  NavbarLayoutProjectsIdSubmitRoute: NavbarLayoutProjectsIdSubmitRoute,
}

const NavbarLayoutRouteWithChildren = NavbarLayoutRoute._addFileChildren(
  NavbarLayoutRouteChildren,
)

interface DomainsRouteChildren {
  DomainsSlugRoute: typeof DomainsSlugRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsSlugRoute: DomainsSlugRoute,
  DomainsIndexRoute: DomainsIndexRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  NavbarLayoutRoute: NavbarLayoutRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DomainsRoute: DomainsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  ApiCronCleanupSessionsRoute: ApiCronCleanupSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
